### ISSUE TITLE
Consider bringing back "Network Address"

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#89] opened 2018-03-28 14:06 UTC
Mentioned by @henkbirkholz .

**Comment by adammontville** [comment] 2018-03-30 13:36
Henk mentioned that we might like to bring back the term "Network Address". Here's what that looked like:

>Network Address:  Network addresses are layer specific and follow layer specific address schemes.  Each interface of a specific layer can be associated with one or more addresses appropriate for that layer.  There is no guarantee that an address is globally unique.  In general, there is a scope to an address in which it is intended to be unique.

>Examples include: physical Ethernet port with a MAC address, layer 2 VLAN interface with a MAC address, layer 3 interface with multiple IPv6 addresses, layer 3 tunnel ingress or egress with an IPv4 address.

What if we change this to something like the following:

>Network Address: An address that is layer-specific and follows layer-specific address schemes.

>Each interface of a specific layer can be associated with one or more addresses appropriate for that layer, and there is no guarantee that an address is globally unique, though there is generally a network scope to which the address is intended to be unique. Examples of network addresses include: A physical ethernet port with a MAC address, a layer 2 VLAN interface with a MAC address, a layer 3 interface with multiple IPv6 addresses, a layer 3 tunnel ingress or egress with an IPv4 address.

**Comment by jarrettlu** [comment] 2018-04-03 17:29
While the statements about Network Address may be all correct, why does the term belong to SACM terminology? Are we missing some expositional text here? If network address deserves extra attention in SACM context, that should be spelled out to justify the term's presence in the terminology draft.

**Comment by adammontville** [comment] 2018-04-04 13:53
That's a good question, Jarrett. To me, we don't need to bring this back.

**Comment by sacm** [comment] 2018-04-04 14:00
Hi,

I agree w/ Jarrett.  Please, let's not have SACM redefining terms as basic
as "Network Address".

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by henkbirkholz** [comment] 2018-04-04 18:49
The terminology document provides additional clarification on a surprisingly under-defined term here. We most certainly do not intend to redefine anything - if this is the case, we would really appreciate help with this text - but I am under the impression that we do not redefine it. Over 12 people chimed in to create the initial wording. As with https://github.com/sacmwg/draft-ietf-sacm-terminology/issues/64, if there is an existing definition that elaborates on the quality of network addresses and their application as identifying information elements (e.g. composition of target endpoints), we can just include a reference in an architecture document. But we were not able to find a standard or specification that elaborates on the fact that addresses are -never- guaranteed to be unique (and are only intended to be unique, therefore require separate measures to ensure uniqueness in a given scope that are out of scope) by themselves, which is the reason why we word-smithed the term in Yokohama so much.

**Comment by henkbirkholz** [comment] 2018-04-04 18:53
added a "not" that was missing and unfortunately really distorted the msg to be conveyed...

**Comment by jarrettlu** [comment] 2018-04-04 18:54
Henk provided more background on why the Network Address term appeared in SACM terminology draft. One person at a past IETF side meeting stated that his site has over 1000 endpoints which could be identified by network address. The intent of the Network Address term is to point out the potential trouble of using network address alone to identify endpoint. If the WG agrees that the terminology draft should address this, I can try to propose some expositional text for the term.

**Comment by sacm** [comment] 2018-04-04 19:28
Hi,

Although Henk disliked my objection to a SACM definition of "Network
Address",
I refer you to the 2005 (!) RFC 4001 "Textual Conventions for Internet
Network
Addresses" used in thousands of IETF, IEEE, and vendor MIBs (and contains a
good discussion of uniqueness as well, and IPv4 / IPv6 with or without
zones).

This particular wheel dates from a previous geological era...

Cheers,
- Ira




Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by henkbirkholz** [comment] 2018-04-04 20:03
We were considering using 4001 (or 4007 for that matter), but these references are layer 3 only. Every "network address" used (be it deprecated or experimental) shares this lack of guaranteed uniqueness. It is actually possible - though admittedly rare - to find two NIC with the same vendor supplied MAC address.

If pooling references is enough, we could aggregate a list of definitions from e.g. 4001, 4007, 7348, 802.1q, and so on. If the WG is more comfortable with that approach, I would propose to summarize the characteristics vital to SACM - ideally in a sentence - and then just include the reference. Would that address this issue?

**Comment by adammontville** [comment] 2018-04-04 20:06
It would be good to take a quick first crack at that, Henk. Then we can talk about that...

**Comment by sacm** [comment] 2018-04-04 20:32
Hi Henk,

Umm...the real definition of "Network Address" *is* layer 3 (in both IETF
Internet and ITU-T OSI
protocol stacks).  What else were you thinking of conflating w/ Network
Address?

Any vendor shipping a duplicate MAC address with a different vendor is
breaking their license
agreement with IEEE for a registered OUI - don't buy their garbage
equipment.

Cheers,
- Ira




Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by adammontville** [comment] 2018-04-04 21:17
Ira, thanks for mentioning this. The original definition contained expositional text suggesting that the SACM view of "network address" is something more than layer 3 alone: "Each interface of a specific layer can be associated with one or more addresses appropriate for that layer, and there is no guarantee that an address is globally unique, though there is generally a network scope to which the address is intended to be unique. Examples of network addresses include: A physical ethernet port with a MAC address, a layer 2 VLAN interface with a MAC address, a layer 3 interface with multiple IPv6 addresses, a layer 3 tunnel ingress or egress with an IPv4 address."

Then, it would seem that using "network address", given it's common use in the field, should not be used to mean more than what it is, and we should talk about each specific type of address or create some different, SACM-specific term (I don't think I'd recommend this, but there may be a persuasive argument).

**Comment by sacm** [comment] 2018-04-04 21:26
Hi Adam,

Ah.  Now I think I see your problem w/ "network address" in SACM.  Given
such a fuzzy
concept (any layer from 1 to at least 4 or 5), what's the utility of
collecting such a an
eye-of-the-beholder attribute in SACM?

Cheers,
- Ira


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Jan-April: 579 Park Place  Saline, MI  48176  734-944-0094
May-Dec: PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by henkbirkholz** [comment] 2018-04-04 21:50
In the process of selecting identifying information elements in 2015, network addresses of any kind were constantly top of the list wrt to current practice.

Maybe the whole concept has to be revised. If it is considered an "eye-of-the-beholder" IE in the taxonomy of IE, we should not include it in the information model. This question should be put the WG list instead being a terminology issue. The inclusion of the term was intended to provide expositional text that does not belong into the information model document. If the concept of utilizing layer specific network addresses as identifying information elements is to fuzzy, this is an information model issue and not a terminology issue,

**Comment by henkbirkholz** [comment] 2018-04-04 23:09
> Umm...the real definition of "Network Address" *is* layer 3 (in both IETF Internet and ITU-T OSI protocol stacks)

I am having a hard time finding a corresponding definition that is layer 3 specific in ITU-T (via https://www.itu.int/ITU-R/go/terminology-database).

In the context of OSI layers, ISO/IEC 7498-3:1997 defines that "the Network Layer uniquely identifies each of the end open systems by their network address. This may be independent of the addressing needed by the underlaying layers.". Please mind that this standard is current.

In the IETF of course, network address is very often synonymously used for IP address, but as RFC 4001 correctly states, it is actually Internet Network Address.

We were working under assumption that both "network layer address" and "internet network address" are more specific (because they refer to layer 3) than the general term "network address". I also think that referring to OSI layer related text in this domain is a double sided sword as it contradicts, for example, RFC 4001, significantly.

Maybe I am missing something very obvious here. Am I mistaken to think that the definition provided by -13 was WG consensus?

**Comment by jarrettlu** [comment] 2018-04-05 00:30
I am inclined to think that terminology draft (version 13 or otherwise) is a work produced by the terminology team. Although it's available for the WG to review and provide comments, I don't believe it's widely reviewed by the WG. I don't recall receiving many review comments. 
My general thoughts on this issue are: (1) we should avoid redefine Network Address, (2) expositional text, such as "SACM implementer beware that network addresses aren't unique and should not be used as the sole identifier of endpoint", may be useful. But I'm not certain whether this kind helpful notes should be in the terminology draft.

**Comment by adammontville** [comment] 2018-04-05 01:49
To me, there’s an easy

**Comment by adammontville** [comment] 2018-04-05 01:54
Who knew you could send an email by swiping up??

As I was starting to type, I think there’s an easy solution to this based largely on some of Henk’s recent comments. I think what wasn’t clear to some of us (me, at least) was that the term network address was being used as a parent to two more specific, formal terms - namely, internet network address and network layer address. From a semantic perspective, this makes complete sense to me - it’s the natural is-a relationship.

For example, an internet network address *is a* network address *that is responsible for addressing endpoints at layer 3*.... Or something like that. Then, for the purposes of SACM (provided we do not want to rely exclusively on layer 3 addressing), it makes sense to specify that network address encompasses more than the common shorthand it might normally represent for internet network address and/or network layer address.

This is a simple thing to do, seems to be semantically sound, and would (I think) keep everyone happy about the term’s inclusion in the terminology draft.

Thoughts?

Adam

**Closed as completed** 2018-05-01 15:43 UTC
